baseURL = "https://han5-011ivand3r.github.io/tTales/"
title = "tTales"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "hans-ollivander"
googleAnalytics = ""


Paginate = 6
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Overthought thoughts"
title404 = "This content is not available in your country."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Han5011ivand3r"
startYear = "2020"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = false
taxonomyCloudShuffle = true
accentColor = "#e192c5"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "hanshubham@gmail.com"
github = "han5-011ivand3r"
instagram = "han5_011ivand3r"
twitter = "han5_011ivand3r"
youtube = "UC7sDyB_GMt2-T2HmHswEvjw"

[params.comments]
enable = true

[params.search]
client = "fuse" # algolia / fuse / lunr

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Latest"
weight = -100
url = "/"

[[menu.main]]
name = "Posts"
weight = -90
url = "/posts/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.es]
lang = "es"
languageName = "Spanish"
weight = 1

publishDir = "docs"